config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'favorites/index'
  get 'sessions/new'
  resources :favorites, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new,:create,:show,:edit,:update]
  resources :pictures do
    collection do
      post :confirm

    end
    get :favorites, on: :collection
  end

  scope "(:locale)", locale: /en|ja/ do
    resources :books
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
 # user_id と picture_idの組み合わせを一意性のあるものにしている
  validates :user_id, uniqueness: { scope: :picture_id }
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def set_locale # ロケールのパラメータが設定されていない場合にはデフォルトのロケールを設定するという処理
     I18n.locale = params[:locale] || I18n.default_locale
  end

  def login_required
    redirect_to new_session_path unless current_user
  end

  def default_url_options # URLパラメータにロケール情報を渡すという処理
    { locale: I18n.locale }
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_pictures
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # before_action :ensure_user, only: %i[ show edit update destroy ]
  before_action :set_picture, only: %i[ show edit update destroy ]
  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
    unless @picture.user == current_user
      redirect_to  pictures_path
    end
  end

  # POST /pictures or /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # @picture = Picture.find(params[:id])
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)

    render :new if @picture.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def picture_params
    params.require(:picture).permit(:image, :image_cache,:content)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end


  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "情報を編集しました！"
      redirect_to user_path
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:image,:image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if %w[new create ].include?(action_name)
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/favorites/index.html.erb
<h1><%= current_user.name %>のお気に入り</h1>
<table>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name%></td>
        <td><%= image_tag favorite.image.url if favorite.image.present? %></td>
        <td><%= favorite.content %></td>
      </tr>
    <% end %>


  </tbody>
</table>
<%= link_to "Picture", pictures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithPicture</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      お気に入りの動物の写真を投稿しよう
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
    <footer >taiga.inc </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true ,url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
    <%= form.file_field  :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>

  <%=@picture.content%>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.user.name%></td>
        <td><%= image_tag picture.image.url if picture.image.present? %></td>
        <td><%= picture.content %></td>
        <td><%= link_to 'Show', picture %></td>
        <% if picture.user == current_user %>
         <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
         <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% else %>
       <td></td>
       <td></td>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>
<%= link_to 'favorite', favorites_index_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% if @picture.user == current_user %>
  <%= link_to 'Edit', edit_picture_path(@picture) %> |
<% else %>

<% end %>

<%= link_to 'Back', pictures_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :image %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>


  <div class="submit_record">
    <p><%= f.submit "内容変更" %></p>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= f.hidden_field :image_cache %>



  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>Image:</strong>
   <%= image_tag @user.image.url if @user.image && @user.image.url %>



<%= link_to 'New picture', new_picture_path %>

<%= link_to "Picture", pictures_path %>
<%= link_to "Edit", edit_user_path %>